name: "CI"

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/phpinsights.yml"
    branches: [ main ]
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/phpinsights.yml"
    branches: [ main ]

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!

      - name: Install PHP Insights
        run: |
          curl -OL https://getcomposer.org/download/latest-2.x/composer.phar
          php composer.phar global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          php composer.phar global require nunomaduro/phpinsights
          php composer.phar clearcache -q
          php ~/.composer/vendor/bin/phpinsights --version

      - uses: Novusvetus/action-phpinsights@1.1.16
        with:
          files: "**.php"
          scan_all: true
          phpinsights_path: "php ~/.composer/vendor/bin/phpinsights"
          min_quality: 50
          min_complexity: 50
          min_architecture: 20
          min_style: 20
