name: reviewdog-semgrep
on: [push]
jobs:
  linter_name:
    name: Run Quality Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g-wilson/action-semgrep@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          filter_mode: file
          semgrep_config: p/gosec
